"""change name to first_name and secret_name to last_name

Revision ID: 548fe7d68c7e
Revises: 411c25aa45ec
Create Date: 2023-12-05 22:22:00.447159

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "548fe7d68c7e"
down_revision: Union[str, None] = "411c25aa45ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hero", sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), server_default="Unknown", nullable=False)
    )
    op.add_column(
        "hero", sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), server_default="Unknown", nullable=False)
    )
    op.drop_index("ix_hero_name", table_name="hero")
    op.create_index(op.f("ix_hero_first_name"), "hero", ["first_name"], unique=False)
    op.create_index(op.f("ix_hero_last_name"), "hero", ["last_name"], unique=False)
    op.drop_column("hero", "secret_name")
    op.drop_column("hero", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hero", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.add_column("hero", sa.Column("secret_name", sa.VARCHAR(), nullable=False))
    op.drop_index(op.f("ix_hero_last_name"), table_name="hero")
    op.drop_index(op.f("ix_hero_first_name"), table_name="hero")
    op.create_index("ix_hero_name", "hero", ["name"], unique=False)
    op.drop_column("hero", "last_name")
    op.drop_column("hero", "first_name")
    # ### end Alembic commands ###
