"""add abilities

Revision ID: 9da90d5443a2
Revises: 548fe7d68c7e
Create Date: 2023-12-08 23:22:04.175794

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9da90d5443a2"
down_revision: Union[str, None] = "548fe7d68c7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ability",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hero_ability_link",
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("ability_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ability_id"],
            ["ability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hero_id"],
            ["hero.id"],
        ),
        sa.PrimaryKeyConstraint("hero_id", "ability_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hero_ability_link")
    op.drop_table("ability")
    # ### end Alembic commands ###
