"""update HeroAbility

Revision ID: efbd7203883f
Revises: 6c84d534d955
Create Date: 2023-12-09 23:49:33.144426

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # NEW

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efbd7203883f"
down_revision: Union[str, None] = "6c84d534d955"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hero_ability_link",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    )
    op.add_column(
        "hero_ability_link",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
    )
    op.add_column(
        "team", sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False)
    )
    op.add_column(
        "team", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "updated_at")
    op.drop_column("team", "created_at")
    op.drop_column("hero_ability_link", "updated_at")
    op.drop_column("hero_ability_link", "created_at")
    # ### end Alembic commands ###
